apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: client
  name: svc-client
spec:
  ports:
  - name: svc-port
    port: 8080
    targetPort: frontend
  selector:
    app.kubernetes.io/component: client
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: client
  name: client
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        app.kubernetes.io/component: client
    spec:
      containers:
      - command:
        - /static-web-server
        - --root=/static
        - --health
        - --port=8080
        - --host=0.0.0.0
        - --page-fallback=/static/index.html
        image: ghcr.io/static-web-server/static-web-server:2
        name: default
        ports:
        - containerPort: 8080
          name: frontend
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 1000m
            memory: 256Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /static
          name: dist
      initContainers:
      - command:
        - sh
        - -c
        - cp -r dist/* /static
        image: weatherclient
        name: copy-static
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 1000m
            memory: 256Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /static
          name: dist
      volumes:
      - emptyDir:
          sizeLimit: 256Mi
        name: dist
